# Generated by Django 3.0.6 on 2020-05-14 18:21

import b_project_feed.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('b_project_feed', '0003_profile_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='feature_rating')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Email Address must be entered for verification', regex='^[a-z0-9\\._]+@\\w+\\.\\w{2,3}$')], verbose_name='location_email')),
                ('name', models.CharField(max_length=100, verbose_name='location_name')),
                ('address', models.CharField(max_length=50, verbose_name='location_address')),
                ('city', models.CharField(max_length=50, verbose_name='location_city')),
                ('zipcode', models.CharField(max_length=10, verbose_name='location_zip')),
                ('website', models.URLField(blank=True, verbose_name='location_website')),
                ('phone', models.CharField(max_length=10, verbose_name='location_phone')),
                ('business_hours', models.CharField(max_length=50, verbose_name='location_hours')),
                ('res_join', models.DateTimeField(auto_now_add=True, verbose_name='date_res_join')),
                ('res_mod', models.DateTimeField(auto_now=True, verbose_name='date_res_mod')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='main_rating')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Email Address must be entered for verification', regex='^[a-z0-9\\._]+@\\w+\\.\\w{2,3}$')], verbose_name='user_email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.TextField(default='No Favorites Yet!', verbose_name='user_favorites'),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.URLField(blank=True, verbose_name='shared_links'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Portland, OR', max_length=30, verbose_name='profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='registration',
            field=models.CharField(default=b_project_feed.models.code_registration, max_length=15, verbose_name='registration_code'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='owner'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to=settings.AUTH_USER_MODEL),
        ),
    ]
