# Generated by Django 3.0.6 on 2020-05-14 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_project_feed', '0004_auto_20200514_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='review_comment')),
                ('com_create', models.DateTimeField(auto_now_add=True, verbose_name='date_comment_created')),
                ('com_mod', models.DateTimeField(auto_now=True, verbose_name='date_comment_modified')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='b_project_feed.Reviews')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
