# Generated by Django 3.0.6 on 2020-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_project_feed', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='category_name')),
            ],
        ),
    ]
